version: '3'

services:
  consulserver01:
    build: .
    image: consul_server
    container_name: consulserver01
    hostname: consulserver01
    command: "/tmp/entrypoint.sh"
    ports:
      - "8500:8500"
    networks:
      consul:
        ipv4_address: 172.21.0.2
    volumes:
      - ./servers/server01:/etc/consul.d
  consulserver02:
    image: consul_server
    container_name: consulserver02
    hostname: consulserver02
    command: "/tmp/entrypoint.sh"
    networks:
      consul:
        ipv4_address: 172.21.0.3
    volumes:
      - ./servers/server02:/etc/consul.d
  consulserver03:
    image: consul_server
    container_name: consulserver03
    hostname: consulserver03
    command: "/tmp/entrypoint.sh"
    networks:
      consul:
        ipv4_address: 172.21.0.4
    volumes:
      - ./servers/server03:/etc/consul.d
  consulclient01:
    image: consul_server
    container_name: consulclient01
    hostname: consulclient01
    command: "/tmp/entrypoint.sh"
    networks:
      consul:
        ipv4_address: 172.21.0.5
    volumes:
      - ./clients/consul01:/etc/consul.d
  consulclient02:
    image: consul_server
    container_name: consulclient02
    hostname: consulclient02
    command: "/tmp/entrypoint.sh"
    networks:
      consul:
        ipv4_address: 172.21.0.6
    volumes:
      - ./clients/consul02:/etc/consul.d

networks:
  consul:
    driver: bridge
    ipam:
     config:
      - subnet: 172.21.0.0/16